// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 튜토리얼 사이드바는 tutorial.md 파일만 포함하도록 수동으로 정의합니다.
  // userGuideSidebar: ['userGuide', 'how-to-use'],
  userGuideSidebar: [
    {
      type: 'autogenerated',
      dirName: 'user-guide/introduction'
    },
    {
      type: 'autogenerated',
      dirName: 'user-guide/tutorial'
    },
    {
      type: 'autogenerated',
      dirName: 'user-guide/faq'
    },
  ],

  devGuideSidebar: [
    {
      type: 'category',
      label: '시스템 개요',
      link: {
        type: 'doc',
        id: 'dev-guide/system-overview/index',
      },
      items: [
        'dev-guide/system-overview/architecture',   
        'dev-guide/system-overview/data-flow',      
        'dev-guide/system-overview/environment',
      ]
    },

    {
      type: 'category',
      label: '감정 분석 모델',
      link: {
        type: 'doc',
        id: 'dev-guide/ai-model/index',
      },
      items: [
        'dev-guide/ai-model/model-overview',
        'dev-guide/ai-model/prompt-rules', 
      ]
    },

    {
      type: 'category',
      label: '운영 배포',
      link: {
        type: 'doc',
        id: 'dev-guide/deploy/index',
      },
      items: [
        'dev-guide/deploy/build-deploy',  
        'dev-guide/deploy/versioning',   
      ]
    },
  ],

  apiSidebar: [{type: 'autogenerated', dirName: 'dajeong-api'}],
};

export default sidebars;
